import {StyleSheet, Dimensions} from 'react-native';

const ScreenWidth = Dimensions.get('window').width;
const ScreenHeight = Dimensions.get('window').height;

export const weatherStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: ScreenHeight * 1,
    //backgroundColor: '#E5E7EA',
  },
  header: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 65,
    width: ScreenWidth * 1,
    backgroundColor: 'slateblue',
  },
  indicator: {
    marginTop: 65,
  },
  content: {
    flex: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 65,
  },
  section1: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 450,
    width: ScreenWidth * 1,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    backgroundColor: 'slateblue',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: ScreenWidth * 0.85,
    paddingHorizontal: 25,
    paddingVertical: 3,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderRadius: 60,
    borderColor: '#C0C0C0',
    borderWidth: 0.3,
    alignSelf: 'flex-end',
    marginRight: 15,
    marginTop: 5,
  },
  input: {flex: 1},
  search: {
    paddingVertical: 10,
    color: 'rgba(255,255,255,0.6)',
  },
  errorText: {marginBottom: 6, fontSize: 16, color: 'slateblue'},
  locationContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  location: {
    color: '#FFFF',
    textAlign: 'center',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 20,
    marginRight: 10,
  },
  current: {
    color: '#FFFF',
    fontSize: 36,
    textAlign: 'center',
    fontWeight: 'bold',
    marginTop: 30,
  },
  date: {
    color: '#f1f1f1',
    textAlign: 'center',
    fontStyle: 'normal',
    fontSize: 18,
  },
  tempContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 55,
  },
  main: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 18,
    marginRight: 25,
    marginTop: -30,
  },
  mainContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
  },
  temp: {
    color: '#FFFF',
    fontSize: 40,
    textAlign: 'center',
    fontWeight: 'bold',
    marginTop: 5,
    marginLeft: 20,
  },
  temperature: {
    color: '#FFFF',
    fontSize: 40,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  weatherIcon: {
    width: 120,
    height: 120,
  },
  detailContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
    marginTop: 70,
  },
  detailImage: {
    width: ScreenWidth * 0.11,
    resizeMode: 'contain',
    flexDirection: 'row',
  },
  textContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
  },
  text: {
    color: '#f1f1f1',
    fontSize: 14,
  },
  textPressure: {
    marginLeft: -15,
  },
  section2: {
    marginTop: 520,
  },
  card: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: -40,
  },
});
